/* A1: is a bit-exact Metal fp8 matmul possible using double-float for the block accumulation?
 *
 * The CPU reference here is the REAL engine code: we #include quant.h and call matmul_fp8
 * directly, so there is no transcription risk. The Metal LUT is generated by calling the engine's
 * own e4m3_decode(0..255), so the shader cannot drift from the C table either.
 *
 * MODE 0 = plain float outer accumulator  -> expected to FAIL (this is the RED case, and it proves
 *          the double-float machinery is actually necessary rather than cargo-culted)
 * MODE 1 = double-float outer accumulator -> expected to PASS 0 ULP
 */
#import <Metal/Metal.h>
#import <Foundation/Foundation.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <mach/mach_time.h>

/* quant.h's matmul_fp8 references these (added for the E66d min-product tracker). */
float coli_fp8_minprod = 3.4e38f;
int   coli_fp8_minprod_enabled = 0;
#include "../../c/quant.h"

static double now_s(void){ static mach_timebase_info_data_t tb; if(!tb.denom) mach_timebase_info(&tb);
  return (double)mach_absolute_time()*tb.numer/tb.denom/1e9; }
static uint32_t B32(float f){ uint32_t u; memcpy(&u,&f,4); return u; }

static const char *SRC =
"#include <metal_stdlib>\n using namespace metal;\n"
"struct df { float hi; float lo; };\n"
"inline df two_sum(float a, float b){ float s=a+b, bb=s-a, e=(a-(s-bb))+(b-bb); return df{s,e}; }\n"
"inline df two_prod(float a, float b){ float p=a*b, e=fma(a,b,-p); return df{p,e}; }\n"
"inline df df_add_prod(df acc, float a, float b){\n"
"  df p = two_prod(a,b);\n"
"  df s = two_sum(acc.hi, p.hi);\n"
"  float lo = s.lo + (acc.lo + p.lo);\n"
"  return two_sum(s.hi, lo);\n"
"}\n"
"kernel void fp8mm(device const uchar*  W   [[buffer(0)]],\n"
"                  device const float*  SC  [[buffer(1)]],\n"
"                  device const float*  X   [[buffer(2)]],\n"
"                  device float*        Y   [[buffer(3)]],\n"
"                  device const float*  LUT [[buffer(4)]],\n"
"                  constant uint4&      d   [[buffer(5)]],\n"   // O, I, S, nblkI
"                  constant uint&       mode[[buffer(6)]],\n"
"                  uint2 gid [[thread_position_in_grid]]) {\n"
"  uint O=d.x, I=d.y, S=d.z, NB=d.w;\n"
"  uint o=gid.x, s=gid.y;\n"
"  if (o>=O || s>=S) return;\n"
"  device const uchar *w = W + (ulong)o*I;\n"
"  device const float *x = X + (ulong)s*I;\n"
"  device const float *scl = SC + (ulong)(o/128u)*NB;\n"
"  df a = df{0.0f, 0.0f};\n"
"  float aplain = 0.0f;\n"
"  for (uint bi=0; bi<NB; ++bi) {\n"
"    uint base = bi*128u; uint blen = (base+128u > I) ? (I-base) : 128u;\n"
"    float acc = 0.0f;\n"
"    for (uint i=0; i<blen; ++i) acc += LUT[w[base+i]] * x[base+i];\n"
"    if (mode==1u) a = df_add_prod(a, acc, scl[bi]);\n"
"    else          aplain += acc * scl[bi];\n"
"  }\n"
"  Y[(ulong)s*O + o] = (mode==1u) ? (a.hi + a.lo) : aplain;\n"
"}\n";

typedef struct { const char *name; int O, I; } Shape;

int main(int argc, char **argv){ @autoreleasepool {
  int mode = argc>1 ? atoi(argv[1]) : 1;
  int S    = argc>2 ? atoi(argv[2]) : 64;
  Shape shapes[] = {
    {"wq_a  I=4096 O=1024",  1024, 4096},
    {"wq_b  I=1024 O=32768",32768, 1024},
    {"wkv   I=4096 O=512",    512, 4096},
    {"wo_b  I=1024 O=4096",  4096, 1024},
  };
  id<MTLDevice> dev = MTLCreateSystemDefaultDevice();
  id<MTLCommandQueue> q = [dev newCommandQueue];
  NSError *err=nil;
  MTLCompileOptions *opt=[MTLCompileOptions new];
  opt.fastMathEnabled = NO;   /* CRITICAL: fast math destroys Dekker two_sum/two_prod */
  id<MTLLibrary> lib=[dev newLibraryWithSource:[NSString stringWithUTF8String:SRC] options:opt error:&err];
  if(!lib){ printf("  shader compile FAILED: %s\n",[[err localizedDescription]UTF8String]); return 2; }
  id<MTLComputePipelineState> pso=[dev newComputePipelineStateWithFunction:[lib newFunctionWithName:@"fp8mm"] error:&err];
  if(!pso){ printf("  pipeline FAILED\n"); return 2; }

  /* LUT generated from the engine's own decoder - cannot drift from the C table */
  id<MTLBuffer> LUT=[dev newBufferWithLength:256*sizeof(float) options:MTLResourceStorageModeShared];
  { float *l=LUT.contents; for(int c=0;c<256;c++) l[c]=e4m3_decode((uint8_t)c); }

  printf("  mode=%s  S=%d\n", mode==1?"double-float (expect 0 ULP)":"plain float (RED, expect failures)", S);
  printf("  %-24s %10s %12s %10s  %-12s %-12s %s\n","shape","outputs","differing","verdict","cpu","gpu","speedup");
  int total_bad=0; double tot_cpu=0, tot_gpu=0;
  for(int si=0; si<4; ++si){
    int O=shapes[si].O, I=shapes[si].I;
    int64_t nblkI = fp8_nblk(I);
    size_t wb=(size_t)O*I, sb=(size_t)((O+127)/128)*nblkI*sizeof(float);
    id<MTLBuffer> W =[dev newBufferWithLength:wb options:MTLResourceStorageModeShared];
    id<MTLBuffer> SC=[dev newBufferWithLength:sb options:MTLResourceStorageModeShared];
    id<MTLBuffer> X =[dev newBufferWithLength:(size_t)S*I*4 options:MTLResourceStorageModeShared];
    id<MTLBuffer> Y =[dev newBufferWithLength:(size_t)S*O*4 options:MTLResourceStorageModeShared];
    uint8_t *wp=W.contents; float *sp=SC.contents, *xp=X.contents;
    srandom(1000+si);
    for(size_t i=0;i<wb;i++){ uint8_t b=(uint8_t)(random()&0xFF); if(b==0x7F||b==0xFF) b=0x3C; wp[i]=b; }
    for(size_t i=0;i<sb/sizeof(float);i++) sp[i]=(float)((random()/(double)RAND_MAX)*0.02+0.001);
    for(size_t i=0;i<(size_t)S*I;i++)      xp[i]=(float)((random()/(double)RAND_MAX)*2.0-1.0);

    float *ref = malloc((size_t)S*O*sizeof(float));
    double cbest=1e9;
    for(int it=0; it<3; ++it){ double t0=now_s(); matmul_fp8(ref, xp, wp, sp, S, I, O);
                               double dt=now_s()-t0; if(dt<cbest) cbest=dt; }

    unsigned int d[4]={(unsigned)O,(unsigned)I,(unsigned)S,(unsigned)nblkI};
    unsigned int m=(unsigned)mode;
    id<MTLCommandBuffer> cb=[q commandBuffer];
    id<MTLComputeCommandEncoder> e=[cb computeCommandEncoder];
    [e setComputePipelineState:pso];
    [e setBuffer:W offset:0 atIndex:0]; [e setBuffer:SC offset:0 atIndex:1];
    [e setBuffer:X offset:0 atIndex:2]; [e setBuffer:Y offset:0 atIndex:3];
    [e setBuffer:LUT offset:0 atIndex:4];
    [e setBytes:d length:sizeof(d) atIndex:5];
    [e setBytes:&m length:sizeof(m) atIndex:6];
    [e dispatchThreads:MTLSizeMake(O,S,1) threadsPerThreadgroup:MTLSizeMake(64,1,1)];
    [e endEncoding]; [cb commit]; [cb waitUntilCompleted];
    double gbest=1e9;
    for(int it=0; it<3; ++it){
      double t0=now_s();
      id<MTLCommandBuffer> cb2=[q commandBuffer];
      id<MTLComputeCommandEncoder> e2=[cb2 computeCommandEncoder];
      [e2 setComputePipelineState:pso];
      [e2 setBuffer:W offset:0 atIndex:0]; [e2 setBuffer:SC offset:0 atIndex:1];
      [e2 setBuffer:X offset:0 atIndex:2]; [e2 setBuffer:Y offset:0 atIndex:3];
      [e2 setBuffer:LUT offset:0 atIndex:4];
      [e2 setBytes:d length:sizeof(d) atIndex:5];
      [e2 setBytes:&m length:sizeof(m) atIndex:6];
      [e2 dispatchThreads:MTLSizeMake(O,S,1) threadsPerThreadgroup:MTLSizeMake(64,1,1)];
      [e2 endEncoding]; [cb2 commit]; [cb2 waitUntilCompleted];
      double dt=now_s()-t0; if(dt<gbest) gbest=dt;
    }

    float *got=Y.contents; long bad=0, maxulp=0;
    for(size_t i=0;i<(size_t)S*O;i++){
      if(B32(ref[i])!=B32(got[i])){
        bad++;
        long d2=(long)B32(ref[i])-(long)B32(got[i]); if(d2<0)d2=-d2;
        if(d2>maxulp) maxulp=d2;
      }
    }
    total_bad += (bad!=0);
    printf("  %-24s %10lld %12ld %10s  cpu=%8.2fms gpu=%8.2fms  %5.2fx\n", shapes[si].name,
           (long long)S*O, bad, bad==0?"0 ULP":"DIFFERS", cbest*1e3, gbest*1e3, cbest/gbest);
    tot_cpu += cbest; tot_gpu += gbest;
    free(ref);
  }
  printf("\n  AGGREGATE  cpu=%.2fms gpu=%.2fms  ->  %.2fx\n", tot_cpu*1e3, tot_gpu*1e3, tot_cpu/tot_gpu);
  printf("  RESULT: %s\n", total_bad==0
      ? "ALL SHAPES BIT-EXACT -> bit-exact Metal attention kernel is PROVEN possible"
      : "differences present");
  return total_bad==0?0:1;
} }
